# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-03-09 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to='wish_list_app.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='users',
            field=models.ManyToManyField(related_name='shared_items', to='wish_list_app.User'),
        ),
    ]
